# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SendDown <- function(cutPoint, splitVar, Data, treNodes, direction) {
    .Call(`_rcITR_SendDown`, cutPoint, splitVar, Data, treNodes, direction)
}

estITR <- function(input) {
    .Call(`_rcITR_estITR`, input)
}

estOpt <- function(y, r, trt, prtx, rule, tau, lambda) {
    .Call(`_rcITR_estOpt`, y, r, trt, prtx, rule, tau, lambda)
}

splitConditional <- function(zcut, zcutCat, datMatrix, parameters) {
    .Call(`_rcITR_splitConditional`, zcut, zcutCat, datMatrix, parameters)
}

splitContinuous <- function(zcut, zcutCat, datMatrix, parameters) {
    .Call(`_rcITR_splitContinuous`, zcut, zcutCat, datMatrix, parameters)
}

splitSurvival <- function(zcut, zcutCat, datMatrix, parameters) {
    .Call(`_rcITR_splitSurvival`, zcut, zcutCat, datMatrix, parameters)
}

